/**
 * Document exports. In the prototype these run in the browser; in production the
 * server (Phase D) should produce real .docx and .pdf files with the same layout.
 */
import { DOC_TYPE_LABEL, type AgentDocument } from '../agent';
import { parse, toHtml } from './markdown';

/** Embedded viewers (e.g. the published preview link) block downloads, printing and sharing. */
export const isEmbedded = (() => {
  try {
    return window.self !== window.top;
  } catch {
    return true;
  }
})();

export const canShare = !isEmbedded && typeof navigator.share === 'function';

export const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/[—–]/g, '-')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60);

export const fileBase = (doc: AgentDocument) => `${slug(doc.title)}_${doc.createdAt.slice(0, 10)}${doc.version && doc.version > 1 ? `_v${doc.version}` : ''}`;

const footerLines = (doc: AgentDocument) => [
  `Guardrail: ${doc.guardrail.status}${doc.guardrail.flags.length ? ' — ' + doc.guardrail.flags.join('; ') : ''}`,
  `Sources: ${doc.sources.map((s) => (s.kind === 'drive' ? `${s.title} (Drive)` : s.title)).join(' · ')}`,
  `Saved: ${doc.savedPath ?? 'not saved'}`,
];

/** Markdown with the standard footer from agents/education-agent-procedures.md. */
export function toMarkdown(doc: AgentDocument): string {
  return `${doc.body.trim()}\n\n---\n\n${footerLines(doc).join('  \n')}\n`;
}

/* Print/Word stylesheet: iTOP navy type, lime accents, A4 margins. */
const PRINT_CSS = `
@page { size: A4; margin: 18mm 16mm 20mm; }
body { font-family: 'Work Sans', Arial, Helvetica, sans-serif; color: #0E2841; font-size: 10.5pt; line-height: 1.5; }
.brandbar { border-bottom: 3pt solid #BED243; padding-bottom: 6pt; margin-bottom: 14pt; }
.brand { font-size: 16pt; letter-spacing: -0.5pt; color: #0E2841; }
.brand span { color: #00AED8; }
.meta { font-family: 'JetBrains Mono', Consolas, monospace; font-size: 7.5pt; letter-spacing: 1.2pt; text-transform: uppercase; color: #4F6278; }
h1 { font-weight: normal; font-size: 22pt; line-height: 1.1; margin: 0 0 8pt; letter-spacing: -0.4pt; }
h2 { font-weight: 600; font-size: 12pt; margin: 16pt 0 6pt; padding-top: 6pt; border-top: 0.75pt solid #DDE3EC; }
h3 { font-weight: 600; font-size: 10.5pt; margin: 12pt 0 4pt; }
p { margin: 0 0 7pt; }
ul, ol { margin: 0 0 8pt 16pt; padding: 0; }
li { margin: 0 0 3pt; }
ul.checklist { list-style: none; margin-left: 2pt; }
table { border-collapse: collapse; width: 100%; margin: 4pt 0 10pt; font-size: 9.5pt; }
th { background: #0E2841; color: #fff; text-align: left; font-weight: 600; padding: 4pt 6pt; }
td { border-bottom: 0.75pt solid #DDE3EC; padding: 4pt 6pt; vertical-align: top; }
blockquote { margin: 0 0 8pt; padding: 6pt 10pt; background: #F1F4FB; border-left: 3pt solid #BED243; }
.review { background: #FFF3C4; color: #6B4E00; font-family: 'JetBrains Mono', Consolas, monospace; font-size: 8pt; padding: 1pt 4pt; }
.flags { background: #FFF3C4; padding: 6pt 10pt; margin: 0 0 12pt; }
.foot { margin-top: 18pt; padding-top: 8pt; border-top: 3pt solid #BED243; font-size: 8.5pt; color: #4F6278; }
.foot p { margin: 0 0 3pt; }
`;

/** Standalone HTML document used for Word and PDF. */
export function toPrintHtml(doc: AgentDocument): string {
  const blocks = parse(doc.body);
  // The sheet header already carries the title; drop a leading H1 that repeats it.
  const body = blocks[0]?.type === 'heading' && blocks[0].level === 1 ? blocks.slice(1) : blocks;
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');
  const date = new Date(doc.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

  return `<!doctype html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta charset="utf-8"><title>${esc(doc.title)}</title><style>${PRINT_CSS}</style></head>
<body>
<div class="brandbar"><div class="brand">iTOP<span>.</span></div>
<div class="meta">${DOC_TYPE_LABEL[doc.procedure]} · Version ${doc.version ?? 1} · ${date}</div></div>
<h1>${esc(doc.title)}</h1>
${doc.guardrail.flags.length ? `<div class="flags"><strong>Needs review:</strong> ${doc.guardrail.flags.map(esc).join('; ')}</div>` : ''}
${toHtml(body)}
<div class="foot">${footerLines(doc)
    .map((l) => `<p>${esc(l)}</p>`)
    .join('')}<p>Generated by the iTOP Agent (demo). Clinical content requires clinician review before use.</p></div>
</body></html>`;
}

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

export function downloadWord(doc: AgentDocument) {
  // Word opens HTML saved as .doc with formatting intact. Real .docx comes from the server.
  download(new Blob(['﻿', toPrintHtml(doc)], { type: 'application/msword' }), `${fileBase(doc)}.doc`);
}

export function downloadMarkdown(doc: AgentDocument) {
  download(new Blob([toMarkdown(doc)], { type: 'text/markdown;charset=utf-8' }), `${fileBase(doc)}.md`);
}

/** Opens the system print dialog on the formatted page; "Save as PDF" lives there. */
export function printPdf(doc: AgentDocument) {
  const frame = document.createElement('iframe');
  frame.style.cssText = 'position:fixed;width:0;height:0;border:0;right:0;bottom:0';
  frame.srcdoc = toPrintHtml(doc);
  frame.onload = () => {
    frame.contentWindow?.focus();
    frame.contentWindow?.print();
    setTimeout(() => frame.remove(), 60_000);
  };
  document.body.appendChild(frame);
}

export async function copyText(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.cssText = 'position:fixed;opacity:0';
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand('copy');
    ta.remove();
    return ok;
  }
}

export async function shareDoc(doc: AgentDocument): Promise<void> {
  const md = toMarkdown(doc);
  try {
    const file = new File([toPrintHtml(doc)], `${fileBase(doc)}.doc`, { type: 'application/msword' });
    if (navigator.canShare?.({ files: [file] })) {
      await navigator.share({ title: doc.title, text: doc.title, files: [file] });
      return;
    }
  } catch (e) {
    if ((e as Error).name === 'AbortError') return;
  }
  await navigator.share({ title: doc.title, text: md });
}
